In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving clean_data.csv to clean_data.csv
Saving dadosAlunos20191-20231.csv to dadosAlunos20191-20231.csv
Saving dadosAprovacao20191-20231.csv to dadosAprovacao20191-20231.csv
Saving dadosMatriculas20191-20231.csv to dadosMatriculas20191-20231.csv

In [ ]:
df1 = pd.read_csv('clean_data.csv')
df2 = pd.read_csv('dadosAlunos20191-20231.csv')
df3 = pd.read_csv('dadosAprovacao20191-20231.csv')
df4 = pd.read_csv('dadosMatriculas20191-20231.csv')

In [ ]:
print("Linhas:", df1.shape[0])
print("Colunas:", df1.shape[1])

print("\nNomes das colunas:")
print(df1.columns)

print("\nPrimeiras linhas (para entender o que cada linha representa):")
print(df1.head())

Linhas: 99
Colunas: 23

Nomes das colunas:
Index(['aluno_id', 'sexo', 'dist_cidade_km', 'desistiu', 'ingresso__1',
       'ingresso__2', 'ingresso__3', 'ingresso__4', 'ingresso__5',
       'ingresso__6', 'ingresso__9', 'ingresso__21', 'ingresso__22',
       'ingresso__27', 'ingresso__28', 'ingresso__31', 'ingresso__33',
       'ingresso__34', 'algebra_linear_e_geometria_analitica', 'calculo_i',
       'comunicacao_e_expressao', 'fisica_i', 'fundamentos_de_quimica'],
      dtype='object')

Primeiras linhas (para entender o que cada linha representa):
   aluno_id  sexo  dist_cidade_km  desistiu  ingresso__1  ingresso__2  \
0         1     1            15.5         0            0            0
1         2     1            12.1         0            0            0
2         8     1            16.0         0            0            0
3         9     1            12.1         0            0            0
4        11     1            25.1         0            0            0

   ingresso__3  ingresso__4  ingresso__5  ingresso__6  ...  ingresso__27  \
0            0            0            0            0  ...             1
1            0            0            1            0  ...             0
2            0            0            1            0  ...             0
3            0            0            1            0  ...             0
4            0            0            0            0  ...             0

   ingresso__28  ingresso__31  ingresso__33  ingresso__34  \
0             0             0             0             0
1             0             0             0             0
2             0             0             0             0
3             0             0             0             0
4             1             0             0             0

   algebra_linear_e_geometria_analitica  calculo_i  comunicacao_e_expressao  \
0                                     0          1                        1
1                                     1          0                        0
2                                     1          1                        1
3                                     1          1                        1
4                                     1          1                        0

   fisica_i  fundamentos_de_quimica
0         1                       1
1         0                       1
2         1                       1
3         0                       1
4         0                       1

[5 rows x 23 columns]

In [ ]:
print("Linhas:", df2.shape[0])
print("Colunas:", df2.shape[1])

print("\nNomes das colunas:")
print(df2.columns)

print("\nPrimeiras linhas (para entender o que cada linha representa):")
print(df2.head())

Linhas: 1414
Colunas: 19

Nomes das colunas:
Index(['i_curso', 'cp_disciplina', 'cp_turma', 'nome_curso', 'cp_semestre',
       'i_saida', 'nome_saida', 'dt_saida', 'i_ingresso', 'nome_ingresso',
       'dt_ingresso', 'sexo', 'i_cidade', 'nome_cid', 'dt_nasc', 'dt_cadastro',
       'nacionalidade', 'estado_civil', 'novoCodigo'],
      dtype='object')

Primeiras linhas (para entender o que cada linha representa):
   i_curso cp_disciplina  cp_turma                   nome_curso  cp_semestre  \
0       11         Todas       NaN                    11-DESIGN        20231
1       11         Todas       NaN                    11-DESIGN        20231
2       14         Todas       NaN  14-ENGENHARIA DE COMPUTAÇÃO        20231
3       14         Todas       NaN  14-ENGENHARIA DE COMPUTAÇÃO        20231
4       14         Todas       NaN  14-ENGENHARIA DE COMPUTAÇÃO        20231

   i_saida       nome_saida dt_saida  i_ingresso  \
0        1  SEM FORMA SAÍDA      NaN          22
1        1  SEM FORMA SAÍDA      NaN          22
2        1  SEM FORMA SAÍDA      NaN           5
3        1  SEM FORMA SAÍDA      NaN          34
4        1  SEM FORMA SAÍDA      NaN          22

                             nome_ingresso                 dt_ingresso sexo  \
0                            PROUNI - 100%  08/12/2022 11:36:25:396362    M
1                            PROUNI - 100%   08/12/2022 11:36:25:36129    F
2                              REMATRICULA  08/12/2022 11:36:30:372695    M
3  SELEÇÃO SIMPLIFICADA - TÉCNICO DE VALOR  28/02/2023 20:28:59:287668    F
4                            PROUNI - 100%  08/12/2022 11:36:22:624537    M

   i_cidade     nome_cid     dt_nasc                 dt_cadastro  \
0      42.0        TURVO  21/07/1996     13/02/2019 15:59:11:831
1       1.0     CRICIÚMA  23/11/2001     04/02/2019 19:47:49:687
2       2.0        IÇARA  23/10/2001     12/02/2020 19:49:48:979
3       1.0     CRICIÚMA  14/07/2004  28/02/2023 20:28:59:267318
4      28.0  NOVA VENEZA  22/05/1980     06/03/2018 17:26:37:323

  nacionalidade estado_civil  novoCodigo
0    BRASILEIRA            S       272.0
1    BRASILEIRA            S       274.0
2    BRASILEIRA            S        89.0
3    BRASILEIRA            S       210.0
4    BRASILEIRA            C        28.0

In [ ]:
print("Linhas:", df3.shape[0])
print("Colunas:", df3.shape[1])

print("\nNomes das colunas:")
print(df3.columns)

print("\nPrimeiras linhas (para entender o que cada linha representa):")
print(df3.head())

Linhas: 3074
Colunas: 11

Nomes das colunas:
Index(['semestre', 'i_curso', 'nome_cur', 'i_disciplina', 'nome_disc',
       'nome_prof', 'nota_final', 'numero_falta', 'resultado', 'fase',
       'novoCodigo'],
      dtype='object')

Primeiras linhas (para entender o que cada linha representa):
   semestre  i_curso                  nome_cur  i_disciplina    nome_disc  \
0     20192       14  ENGENHARIA DE COMPUTAÇÃO       1402052  PROGRAMAÇÃO
1     20192       14  ENGENHARIA DE COMPUTAÇÃO       1402052  PROGRAMAÇÃO
2     20192       14  ENGENHARIA DE COMPUTAÇÃO       1402052  PROGRAMAÇÃO
3     20192       14  ENGENHARIA DE COMPUTAÇÃO       1402052  PROGRAMAÇÃO
4     20192       14  ENGENHARIA DE COMPUTAÇÃO       1402052  PROGRAMAÇÃO

                nome_prof  nota_final  numero_falta resultado  fase  \
0  DANIEL BASILIO MARCELO         7.3             0         A     2
1  DANIEL BASILIO MARCELO         6.1             0         A     2
2  DANIEL BASILIO MARCELO         4.7            16         R     2
3  DANIEL BASILIO MARCELO         0.7            40         R     2
4  DANIEL BASILIO MARCELO         7.7             4         A     2

   novoCodigo
0           1
1           2
2           3
3           4
4           5

In [ ]:
print("Linhas:", df4.shape[0])
print("Colunas:", df4.shape[1])

print("\nNomes das colunas:")
print(df4.columns)

print("\nPrimeiras linhas (para entender o que cada linha representa):")
print(df4.head())

Linhas: 5828
Colunas: 17

Nomes das colunas:
Index(['i_empresa', 'semestre', 'i_ingresso', 'i_curso', 'nomecurso',
       'i_saida', 'saida', 'dt_saida', 'dt_ingresso', 'observacao', 'usuario',
       'dt_sistema', 'i_disciplina', 'cp_disc', 'i_turma', 'cp_sit',
       'novoCodigo'],
      dtype='object')

Primeiras linhas (para entender o que cada linha representa):
   i_empresa  semestre  i_ingresso  i_curso                      nomecurso  \
0          1     20211          28       14  14 - ENGENHARIA DE COMPUTAÇÃO
1          1     20211          21       14  14 - ENGENHARIA DE COMPUTAÇÃO
2          1     20211          21       14  14 - ENGENHARIA DE COMPUTAÇÃO
3          1     20211          28       14  14 - ENGENHARIA DE COMPUTAÇÃO
4          1     20211          28       14  14 - ENGENHARIA DE COMPUTAÇÃO

   i_saida                  saida                 dt_saida  \
0        1        SEM FORMA SAÍDA                      NaN
1        7   DESISTÊNCIA DE CURSO  28/01/2021 15:11:02:712
2        6  TROCA DE CURSO NA IES   19/07/2021 19:56:28:28
3        1        SEM FORMA SAÍDA                      NaN
4        1        SEM FORMA SAÍDA                      NaN

               dt_ingresso              observacao         usuario  \
0  17/12/2020 11:23:40:145                     NaN  amanda.bettiol
1  23/10/2020 15:08:56:587  IRÁ MORAR EM JOINVILLE   debora.soares
2  07/12/2020 18:09:42:303                     NaN  michele.vottri
3  18/12/2020 18:06:28:318                     NaN   thayse.correa
4  17/12/2020 18:12:25:097                     NaN   thayse.correa

                dt_sistema  i_disciplina           cp_disc  i_turma cp_sit  \
0  17/12/2020 11:23:40:145        190101  190101-CÁLCULO I        1    APR
1  28/01/2021 15:11:14:238        190101  190101-CÁLCULO I        1    NaN
2   19/07/2021 19:56:28:28        190101  190101-CÁLCULO I        1    APR
3  13/07/2021 14:27:29:852        190101  190101-CÁLCULO I        1    APR
4  09/03/2022 09:46:15:927        190101  190101-CÁLCULO I        1    APR

   novoCodigo
0       144.0
1       359.0
2       197.0
3       145.0
4       147.0

In [ ]:
df1.isnull().sum()

aluno_id                                0
sexo                                    0
dist_cidade_km                          0
desistiu                                0
ingresso__1                             0
ingresso__2                             0
ingresso__3                             0
ingresso__4                             0
ingresso__5                             0
ingresso__6                             0
ingresso__9                             0
ingresso__21                            0
ingresso__22                            0
ingresso__27                            0
ingresso__28                            0
ingresso__31                            0
ingresso__33                            0
ingresso__34                            0
algebra_linear_e_geometria_analitica    0
calculo_i                               0
comunicacao_e_expressao                 0
fisica_i                                0
fundamentos_de_quimica                  0
dtype: int64

In [ ]:
df2.isnull().sum()

i_curso             0
cp_disciplina       0
cp_turma         1414
nome_curso          0
cp_semestre         0
i_saida             0
nome_saida          0
dt_saida         1371
i_ingresso          0
nome_ingresso       0
dt_ingresso      1414
sexo                0
i_cidade            3
nome_cid            3
dt_nasc             0
dt_cadastro      1414
nacionalidade      10
estado_civil        4
novoCodigo          0
dtype: int64

In [ ]:
df3.isnull().sum()

semestre        0
i_curso         0
nome_cur        0
i_disciplina    0
nome_disc       0
nome_prof       0
nota_final      0
numero_falta    0
resultado       0
fase            0
novoCodigo      0
dtype: int64

In [ ]:
df4.isnull().sum()

i_empresa          0
semestre           0
i_ingresso         0
i_curso            0
nomecurso          0
i_saida            0
saida              0
dt_saida        5198
dt_ingresso        0
observacao      5612
usuario            0
dt_sistema         0
i_disciplina       0
cp_disc            0
i_turma            0
cp_sit           136
novoCodigo         0
dtype: int64

In [ ]:
print("==== INCONSISTÊNCIAS ENCONTRADAS ====\n")

# DF1
print("DF1:")
print("- dist_cidade_km negativas:", (df1['dist_cidade_km'] < 0).sum())
print("- sexo inválido:", df1[~df1['sexo'].isin(['M','F'])]['sexo'].unique())
print("- desistiu inválido:", df1[~df1['desistiu'].isin([0,1])]['desistiu'].unique())

# DF2
print("\nDF2:")
print("- sexo inválido:", df2[~df2['sexo'].isin(['M','F'])]['sexo'].unique())

# DF3
print("\nDF3:")
print("- notas fora do padrão:", df3[(df3['nota_final'] < 0) | (df3['nota_final'] > 10)].shape[0])
print("- faltas negativas:", (df3['numero_falta'] < 0).sum())
print("- resultados estranhos:", df3['resultado'].unique())

# DF4
print("\nDF4:")
print("- semestres inválidos (ex: negativos):", (df4['semestre'] < 0).sum())

# DATAS (DF2 e DF4)
for nome, df in {"df2": df2, "df4": df4}.items():
    for col in df.columns:
        if 'dt_' in col:
            temp = pd.to_datetime(df[col], errors='coerce')
            erros = temp.isnull().sum()
            if erros > 0:
                print(f"- {nome} coluna {col} tem {erros} datas inválidas")

==== INCONSISTÊNCIAS ENCONTRADAS ====

DF1:
- dist_cidade_km negativas: 0
- sexo inválido: [1 0]
- desistiu inválido: []

DF2:
- sexo inválido: []

DF3:
- notas fora do padrão: 0
- faltas negativas: 0
- resultados estranhos: ['A' 'R']

DF4:
- semestres inválidos (ex: negativos): 0
- df2 coluna dt_saida tem 1371 datas inválidas
- df2 coluna dt_ingresso tem 1414 datas inválidas
- df2 coluna dt_cadastro tem 1414 datas inválidas
- df4 coluna dt_saida tem 5702 datas inválidas
- df4 coluna dt_ingresso tem 5828 datas inválidas
- df4 coluna dt_sistema tem 5828 datas inválidas

In [ ]:
print("==== INCONSISTÊNCIAS REAIS ====\n")

# DF1
print("DF1:")
print("- dist_cidade_km negativas:")
print(df1[df1['dist_cidade_km'] < 0][['aluno_id', 'dist_cidade_km']])

print("\n- desistiu inválido (esperado 0 ou 1):")
print(df1[~df1['desistiu'].isin([0,1])][['aluno_id', 'desistiu']])


# DF3
print("\nDF3:")
print("- notas inválidas (<0 ou >10):")
print(df3[(df3['nota_final'] < 0) | (df3['nota_final'] > 10)]
      [['novoCodigo', 'nome_disc', 'nota_final']])

print("\n- faltas negativas:")
print(df3[df3['numero_falta'] < 0]
      [['novoCodigo', 'nome_disc', 'numero_falta']])


# DF4
print("\nDF4:")
print("- semestres inválidos (<0):")
print(df4[df4['semestre'] < 0][['novoCodigo', 'semestre']])


# DATAS
for nome, df in {"df2": df2, "df4": df4}.items():
    for col in df.columns:
        if 'dt_' in col:
            temp = pd.to_datetime(df[col], errors='coerce')
            erros = df[temp.isnull()]

            if not erros.empty:
                print(f"\n{nome.upper()} - Datas inválidas na coluna {col}:")
                print(erros[['novoCodigo', col]])

==== INCONSISTÊNCIAS REAIS ====

DF1:
- dist_cidade_km negativas:
Empty DataFrame
Columns: [aluno_id, dist_cidade_km]
Index: []

- desistiu inválido (esperado 0 ou 1):
Empty DataFrame
Columns: [aluno_id, desistiu]
Index: []

DF3:
- notas inválidas (<0 ou >10):
Empty DataFrame
Columns: [novoCodigo, nome_disc, nota_final]
Index: []

- faltas negativas:
Empty DataFrame
Columns: [novoCodigo, nome_disc, numero_falta]
Index: []

DF4:
- semestres inválidos (<0):
Empty DataFrame
Columns: [novoCodigo, semestre]
Index: []

DF2 - Datas inválidas na coluna dt_saida:
      novoCodigo dt_saida
0          272.0      NaT
1          274.0      NaT
2           89.0      NaT
3          210.0      NaT
4           28.0      NaT
...          ...      ...
1409       297.0      NaT
1410       115.0      NaT
1411       162.0      NaT
1412       298.0      NaT
1413       169.0      NaT

[1371 rows x 2 columns]

DF2 - Datas inválidas na coluna dt_ingresso:
      novoCodigo dt_ingresso
0          272.0         NaT
1          274.0         NaT
2           89.0         NaT
3          210.0         NaT
4           28.0         NaT
...          ...         ...
1409       297.0         NaT
1410       115.0         NaT
1411       162.0         NaT
1412       298.0         NaT
1413       169.0         NaT

[1414 rows x 2 columns]

DF2 - Datas inválidas na coluna dt_cadastro:
      novoCodigo dt_cadastro
0          272.0         NaT
1          274.0         NaT
2           89.0         NaT
3          210.0         NaT
4           28.0         NaT
...          ...         ...
1409       297.0         NaT
1410       115.0         NaT
1411       162.0         NaT
1412       298.0         NaT
1413       169.0         NaT

[1414 rows x 2 columns]

DF4 - Datas inválidas na coluna dt_saida:
      novoCodigo dt_saida
0          144.0      NaT
1          359.0      NaT
2          197.0      NaT
3          145.0      NaT
4          147.0      NaT
...          ...      ...
5823        79.0      NaT
5824        58.0      NaT
5825        65.0      NaT
5826        86.0      NaT
5827        79.0      NaT

[5702 rows x 2 columns]

DF4 - Datas inválidas na coluna dt_ingresso:
      novoCodigo dt_ingresso
0          144.0         NaT
1          359.0         NaT
2          197.0         NaT
3          145.0         NaT
4          147.0         NaT
...          ...         ...
5823        79.0         NaT
5824        58.0         NaT
5825        65.0         NaT
5826        86.0         NaT
5827        79.0         NaT

[5828 rows x 2 columns]

DF4 - Datas inválidas na coluna dt_sistema:
      novoCodigo dt_sistema
0          144.0        NaT
1          359.0        NaT
2          197.0        NaT
3          145.0        NaT
4          147.0        NaT
...          ...        ...
5823        79.0        NaT
5824        58.0        NaT
5825        65.0        NaT
5826        86.0        NaT
5827        79.0        NaT

[5828 rows x 2 columns]

In [ ]:
print("==== INCONSISTÊNCIAS REAIS ====\n")

# DF1
print("DF1:")
print("- dist_cidade_km negativas:")
print(df1[df1['dist_cidade_km'] < 0][['aluno_id', 'dist_cidade_km']])

print("\n- desistiu inválido (esperado 0 ou 1):")
print(df1[~df1['desistiu'].isin([0,1])][['aluno_id', 'desistiu']])


# DF3
print("\nDF3:")
print("- notas inválidas (<0 ou >10):")
print(df3[(df3['nota_final'] < 0) | (df3['nota_final'] > 10)]
      [['novoCodigo', 'nome_disc', 'nota_final']])

print("\n- faltas negativas:")
print(df3[df3['numero_falta'] < 0]
      [['novoCodigo', 'nome_disc', 'numero_falta']])


# DF4
print("\nDF4:")
print("- semestres inválidos (<0):")
print(df4[df4['semestre'] < 0][['novoCodigo', 'semestre']])


# DATAS (CORRIGIDO)
for nome, df in {"df2": df2, "df4": df4}.items():
    for col in df.columns:
        if 'dt_' in col:
            original = df[col]
            convertido = pd.to_datetime(original, errors='coerce')

            # 🔥 só inválidos reais (não vazios!)
            erros = df[original.notnull() & convertido.isnull()]

            print(f"\n{nome.upper()} - Coluna {col}:")
            print("Vazios:", original.isnull().sum())
            print("Inválidos reais:", erros.shape[0])

            if not erros.empty:
                print("Exemplos de inválidos:")
                print(erros[['novoCodigo', col]].head(10))
            else:
                print("Nenhum valor inválido ✔")

==== INCONSISTÊNCIAS REAIS ====

DF1:
- dist_cidade_km negativas:
Empty DataFrame
Columns: [aluno_id, dist_cidade_km]
Index: []

- desistiu inválido (esperado 0 ou 1):
Empty DataFrame
Columns: [aluno_id, desistiu]
Index: []

DF3:
- notas inválidas (<0 ou >10):
Empty DataFrame
Columns: [novoCodigo, nome_disc, nota_final]
Index: []

- faltas negativas:
Empty DataFrame
Columns: [novoCodigo, nome_disc, numero_falta]
Index: []

DF4:
- semestres inválidos (<0):
Empty DataFrame
Columns: [novoCodigo, semestre]
Index: []

DF2 - Coluna dt_saida:
Vazios: 1371
Inválidos reais: 0
Nenhum valor inválido ✔

DF2 - Coluna dt_ingresso:
Vazios: 1414
Inválidos reais: 0
Nenhum valor inválido ✔

DF2 - Coluna dt_nasc:
Vazios: 0
Inválidos reais: 0
Nenhum valor inválido ✔

DF2 - Coluna dt_cadastro:
Vazios: 1414
Inválidos reais: 0
Nenhum valor inválido ✔

DF4 - Coluna dt_saida:
Vazios: 5702
Inválidos reais: 0
Nenhum valor inválido ✔

DF4 - Coluna dt_ingresso:
Vazios: 5828
Inválidos reais: 0
Nenhum valor inválido ✔

DF4 - Coluna dt_sistema:
Vazios: 5828
Inválidos reais: 0
Nenhum valor inválido ✔